### ISSUE TITLE
trouble building after make clean_all

### ISSUE THREAD

**Issue by nikanar** [ActivityWatch/aw-webui#30]
This morning I tried out `make clean_all`, and now it *seems* aw-webui is having trouble building back. (Maybe it's unrelated, and since I already had trouble with that repos after fooling around in it, maybe it's me who broke something I shouldn't have.) 

```
$ make build
[...]
make[1]: Entering directory '/home/will/15-QS/activitywatch/aw-webui'
npm install

[...]

> node-sass@3.13.1 postinstall /home/will/15-QS/activitywatch/aw-webui/node_modules/node-sass
> node scripts/build.js

Binary found at /home/will/15-QS/activitywatch/aw-webui/node_modules/node-sass/vendor/linux-x64-51/binding.node
Testing binary
Binary is fine
npm WARN vue-loader@8.7.0 requires a peer of babel-runtime@^6.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1600 packages in 80.584s
npm run build

> aw-webui@1.0.0 build /home/will/15-QS/activitywatch/aw-webui
> node build/build.js

[...]

ERROR in ./src/filters.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/number/parse-float' in /home/will/15-QS/activitywatch/aw-webui/src
 @ ./src/filters.js 3:18-69

ERROR in ./src/visualizations/timeline.js
Module not found: Error: Cannot resolve module 'color' in /home/will/15-QS/activitywatch/aw-webui/src/visualizations
 @ ./src/visualizations/timeline.js 14:12-28

ERROR in ./src/visualizations/summary.js
Module not found: Error: Cannot resolve module 'color' in /home/will/15-QS/activitywatch/aw-webui/src/visualizations
 @ ./src/visualizations/summary.js 10:12-28

ERROR in ./src/visualizations/timeline.js
Module not found: Error: Cannot resolve module 'lodash' in /home/will/15-QS/activitywatch/aw-webui/src/visualizations
 @ ./src/visualizations/timeline.js 15:8-25

ERROR in ./src/visualizations/summary.js
Module not found: Error: Cannot resolve module 'lodash' in /home/will/15-QS/activitywatch/aw-webui/src/visualizations
 @ ./src/visualizations/summary.js 11:8-25

ERROR in ./src/util/color.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/keys' in /home/will/15-QS/activitywatch/aw-webui/src/util
 @ ./src/util/color.js 3:12-56

ERROR in ./src/util/color.js
Module not found: Error: Cannot resolve module 'color' in /home/will/15-QS/activitywatch/aw-webui/src/util
 @ ./src/util/color.js 9:12-28
make[1]: Leaving directory '/home/will/15-QS/activitywatch/aw-webui'
cp -r aw-webui/dist/* aw-server/aw_server/static/
make --directory=aw-server build
[...]
```

^ The last paragraphs being in red.

and after that, `make build` fails with :

```
[...]
make[1]: Entering directory '/home/will/15-QS/activitywatch/aw-webui'
npm install
npm WARN vue-loader@8.7.0 requires a peer of babel-runtime@^6.0.0 but none was installed.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/will/.npm/_logs/2017-07-20T14_59_38_892Z-debug.log
make[1]: *** [Makefile:7: build] Error 1
make[1]: Leaving directory '/home/will/15-QS/activitywatch/aw-webui'
make: *** [Makefile:11: build] Error 2
```

complete log said to be /home/will/.npm/_logs/2017-07-20T14_57_53_863Z-debug.log is https://pastebin.com/VqYMkbYq

**Comment by johan-bjareholt** [comment]
That's odd, I just tried to do `make clean` and then `make build` and it worked fine. 

Here's the bottom of your complete log

```
875 verbose stack TypeError: Cannot read property '0' of undefined
875 verbose stack     at rmStuff (/usr/lib/node_modules/npm/lib/unbuild.js:61:24)
875 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
875 verbose stack     at ret (eval at makeNodePromisifiedEval (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
875 verbose stack     at lifecycle.then.then (/usr/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
875 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
875 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
875 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
875 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
875 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
875 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
875 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
875 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
875 verbose stack     at runCallback (timers.js:672:20)
875 verbose stack     at tryOnImmediate (timers.js:645:5)
875 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
```

It seems on the second line that somethings not working as it should with npm, but I'm not sure what.

You are running the same npm version as me (5.3.0) but a older nodejs version (7.10.0, I have 8.1.3), but the node version shouldn't make a diffence.

**Comment by nikanar** [comment]
I re-cloned the repository from scratch and it works, so it must be something I had broken myself. Sorry for the noise.
